export const LIST_BLOG = 'LIST_BLOG';
export const LIST_BLOG_SUCCESS = 'LIST_BLOG_SUCCESS';
export const LIST_BLOG_FAILURE = 'LIST_BLOG_FAILURE';

export const SHOW_BLOG = 'SHOW_BLOG';
export const SHOW_BLOG_SUCCESS = 'SHOW_BLOG_SUCCESS';
export const SHOW_BLOG_FAILURE = 'SHOW_BLOG_FAILURE';