// show all blog
export const LIST_BLOG = 'LIST_BLOG';
export const LIST_BLOG_SUCCESS = 'LIST_BLOG_SUCCESS';
export const LIST_BLOG_FAILURE = 'LIST_BLOG_FAILURE';
// Show single blog
export const SHOW_BLOG = 'SHOW_BLOG';
export const SHOW_BLOG_SUCCESS = 'SHOW_BLOG_SUCCESS';
export const SHOW_BLOG_FAILURE = 'SHOW_BLOG_FAILURE';
// Draft
export const SHOW_PUBLISHED = 'SHOW_PUBLISHED';
export const SHOW_PUBLISHED_SUCCESS = 'SHOW_PUBLISHED_SUCCESS';
export const SHOW_PUBLISHED_FAILURE = 'SHOW_PUBLISHED_FAILURE';
// Draft
export const SHOW_DRAFT = 'SHOW_DRAFT';
export const SHOW_DRAFT_SUCCESS = 'SHOW_DRAFT_SUCCESS';
export const SHOW_DRAFT_FAILURE = 'SHOW_DRAFT_FAILURE';